image: node:latest

cache:
  paths:
    - node_modules/

stages:
    - init
    - build
    - test

init:
  stage: init
  script:
    - echo "Init stage"
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - echo "Test stage"
    - npm run test

build:
  stage: build
  script:
    - echo "Build stage"
    - npm run build